name: Deploy React App to AWS S3
 
on: #tells when this workflow should run
  push: #on push the workflow will get started
    branches:
      - main   # runs when code or changes pushed to main branch

jobs: #tells which tasks should run
  deploy: #here the task is to deploy 
    runs-on: ubuntu-latest #now the task is to create a ubuntu-latest version for the deployment process
 
    steps: #the steps indiacate the work to be doen after creating a runner machine
      
      - name: Checkout code #this ensures the code is downloaded form the github to runner machine
        uses: actions/checkout@v4

      #setting up the packages and dependencies and libraries that are required for the application
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      
      - name: Install dependencies
        run: npm install

      
      - name: Build project
        run: npm run build

     #to host the application live we have to provide aws credentials which are saved as secrets in the github secerets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      #deploy the build to s3 buckets
      - name: Deploy to S3
        run: aws s3 sync dist/ s3://${{ secrets.S3_BUCKET }} --delete

      